# Generated by Django 5.2.7 on 2025-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên trái cây")),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá (VND/kg)"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Tồn kho (kg)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fruits/", verbose_name="Ảnh"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trái cây",
                "verbose_name_plural": "Trái cây",
            },
        ),
    ]
